version: "3.9"
services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PWD: "oracle_password"
      ORACLE_CHARACTERSET: "AL32UTF8"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./init-scripts:/opt/oracle/scripts/setup

  cadastro_service:
    build:
      context: ./cadastro_service
    ports:
      - "8084:8084"
    depends_on:
      - oracle-db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:oracle:thin:@oracle-db:1521/XEPDB1"
      SPRING_DATASOURCE_USERNAME: "C##PROJETO"
      SPRING_DATASOURCE_PASSWORD: "oracle_password"

  cadastro_web:
    build:
      context: ./CadastroWeb
    ports:
      - "8082:8082"
    depends_on:
      - oracle-db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:oracle:thin:@oracle-db:1521/XEPDB1"
      SPRING_DATASOURCE_USERNAME: "C##PROJETO"
      SPRING_DATASOURCE_PASSWORD: "oracle_password"

  processo_service:
    build:
      context: ./processo_service
    ports:
      - "8085:8085"
    depends_on:
      - oracle-db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:oracle:thin:@oracle-db:1521/XEPDB1"
      SPRING_DATASOURCE_USERNAME: "C##PROJETO"
      SPRING_DATASOURCE_PASSWORD: "oracle_password"

volumes:
  oracle-data:
